### ISSUE TITLE
Update the stats w/ additional products 

### ISSUE THREAD

**Issue by LHinson** [rh-uxd/patternfly-analytics#6]
This [spreadsheet](https://docs.google.com/spreadsheets/d/1imrK7QO-3qNtw_yyFFeTW1N6H9xZ76c2bfXSTbovo4w/edit?ts=5e31d6c4#gid=2002517152) identifies additional repos that are not yet tracked. These repos are marked "No" under the "Statistics" column. 

In addition, it would be ideal if the naming matched what is seen in the spreadsheet. I imagine that is a none issue for anything net new. Can we also match existing stats with the names and have this retroactively applied (meaning that stats from June 2019, etc, would also match the naming)?

**Comment by redallen** [comment]
Retroactively name-changing is possible with some scripting. I'll add the new ones and see what I can do.

**Comment by redallen** [comment]
Closed in 375c32f543429fdd5bec10ae2c250ff1cc7e1fa7
